import Navbar from '@/components/Navbar';
import './globals.css';
import { Gabarito } from 'next/font/google';

const gabarittos = Gabarito({ subsets: ['latin'] });

export const metadata = {
  title: 'Anime List',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${gabarittos.className} bg-color-dark`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
